[package]
name = "rx86"
version = "0.1.0"
authors = ["Blair Urish <burace17@gmail.com>"]
edition = "2021"

[dependencies]
bitflags = "2.9.0"
num-conv = "=0.1.0"

[dependencies.num-traits]
version = "0.2"
default-features = false
